# Generated by Django 3.0.6 on 2020-05-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='etc',
        ),
    ]
