# Generated by Django 3.0.6 on 2020-05-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItems',
            new_name='LineItem',
        ),
    ]
