# Generated by Django 3.0.6 on 2020-05-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in cart', 'in cart'), ('pending', 'pending'), ('in locker', 'in locker'), ('picked up', 'picked up')], default='in cart', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('paid', 'paid'), ('completed', 'completed')], default='cart', max_length=10),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.LineItemStatus'),
            preserve_default=False,
        ),
    ]
