# Generated by Django 3.0.6 on 2020-05-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200519_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
