# Generated by Django 3.0.6 on 2020-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200514_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('pending', 'pending'), ('shipped', 'shipped'), ('fulfilled', 'fulfilled')], default='cart', max_length=10),
        ),
    ]
