# Generated by Django 3.0.6 on 2020-05-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200514_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cart', 'cart'), ('pending', 'pending'), ('shipped', 'shipped'), ('fulfilled', 'fulfilled')], default='cart', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Invoice_Status'),
        ),
    ]
