# Generated by Django 3.0.6 on 2020-05-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200514_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice_Status',
            new_name='InvoiceStatus',
        ),
    ]
