# Generated by Django 3.0.6 on 2020-05-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200524_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='user',
        ),
    ]
