# Generated by Django 3.0.6 on 2020-05-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200514_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='status_id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='shop.InvoiceStatus'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='invoice_id',
            field=models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='shop.Invoice'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
    ]
