# Generated by Django 3.0.6 on 2020-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_lineitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_id',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
