# Generated by Django 3.0.6 on 2020-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200526_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
