# Generated by Django 3.0.6 on 2020-05-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200514_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='line_item_id',
            new_name='line_item',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.InvoiceStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default='blur44', on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
            preserve_default=False,
        ),
    ]
