# Generated by Django 3.0.6 on 2020-05-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200526_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_id',
        ),
    ]
