# Generated by Django 3.0.6 on 2020-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200526_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='line_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
