# Generated by Django 3.0.6 on 2020-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200526_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='image_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
