# Generated by Django 3.0.6 on 2020-05-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200528_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='line_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
