# Generated by Django 3.0.6 on 2020-05-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_notification_line_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='password',
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
