# Generated by Django 3.0.6 on 2020-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200530_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='useradditionalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
