# Generated by Django 3.0.6 on 2020-05-31 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200531_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradditionalinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
