# Generated by Django 3.0.6 on 2020-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200531_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
