# Generated by Django 3.0.6 on 2020-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200606_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passcode',
            name='email_passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
