# Generated by Django 3.0.6 on 2020-06-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200606_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passcode',
            old_name='email_passcode',
            new_name='text_passcode',
        ),
    ]
