# Generated by Django 3.0.6 on 2020-06-06 23:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0026_auto_20200606_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassCode',
            new_name='PassKey',
        ),
        migrations.RenameField(
            model_name='passkey',
            old_name='pass_code',
            new_name='text_key',
        ),
        migrations.RenameField(
            model_name='passkey',
            old_name='text_pass_code',
            new_name='url_key',
        ),
    ]
