# Generated by Django 3.0.6 on 2020-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200606_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalinfo',
            name='display_name',
            field=models.CharField(default='display name', max_length=255),
        ),
    ]
